# -*- coding: utf-8 -*-
"""Linear regression 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiREDR-lRQsWNFOtcuU4WtpsGUHOAE11
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("/content/drive/MyDrive/weight-height.csv")
data.head()

data.tail()

data.isnull().sum()

data['Weight'].plot.box()

data.describe()

x = data.iloc[:,1].values

x

y = data.iloc[:,2].values

y

x = x.reshape(-1,1)

x

y = y.reshape(-1,1)

y

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20)

xtrain.size

xtest.size

from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(xtrain,ytrain)



data = data.rename(columns={'Height': 'Weight', 'Weight': 'Height'})

data.head()

data.isnull().sum()

data['Weight'].plot.box()

x = data.iloc[:,1].values

x

y = data.iloc[:,2].values

y

x = x.reshape(-1,1)

x

y = y.reshape(-1,1)

y

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20)

xtrain.size

xtest.size

from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(xtrain,ytrain)

ypred = model.predict(xtest)

ypred

ytest

xtest

plt.scatter(xtrain,ytrain,color='green')
plt.plot(xtrain,model.predict(xtrain),color='blue')
plt.show()

plt.scatter(xtest,ytest,color='green')
plt.plot(xtest,model.predict(xtest),color='blue')
plt.show()

from sklearn.metrics import r2_score
r2 = r2_score(ytest,ypred)
r2

m = model.coef_

c = model.intercept_

m

c

m*241.893563 + c

